"""add deletion flag to models

Revision ID: 4a8013c2448b
Revises: 9b28535849de
Create Date: 2025-12-02 23:00:26.906377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a8013c2448b"
down_revision: Union[str, Sequence[str], None] = "9b28535849de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "breach_exposures", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    op.create_index(
        "ix_breach_exposures_is_deleted",
        "breach_exposures",
        ["is_deleted"],
        unique=False,
    )
    op.add_column(
        "chat_messages", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    op.create_index(
        "ix_chat_messages_is_deleted", "chat_messages", ["is_deleted"], unique=False
    )
    op.add_column(
        "chat_sessions", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    op.create_index(
        "ix_chat_sessions_is_deleted", "chat_sessions", ["is_deleted"], unique=False
    )
    op.add_column(
        "fraud_reports", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    op.create_index(
        op.f("ix_fraud_reports_is_deleted"),
        "fraud_reports",
        ["is_deleted"],
        unique=False,
    )
    op.add_column(
        "indicators_of_compromise",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
    )
    op.create_index(
        op.f("ix_indicators_of_compromise_is_deleted"),
        "indicators_of_compromise",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        "ix_ioc_is_deleted", "indicators_of_compromise", ["is_deleted"], unique=False
    )
    op.add_column(
        "security_advisors", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    op.create_index(
        op.f("ix_security_advisors_is_deleted"),
        "security_advisors",
        ["is_deleted"],
        unique=False,
    )
    op.add_column(
        "threat_alerts", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    op.create_index(
        op.f("ix_threat_alerts_is_deleted"),
        "threat_alerts",
        ["is_deleted"],
        unique=False,
    )
    op.add_column("threat_feeds", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.create_index(
        "ix_threat_feeds_is_deleted", "threat_feeds", ["is_deleted"], unique=False
    )
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.create_index(
        "ix_users_is_active_is_deleted",
        "users",
        ["is_active", "is_deleted"],
        unique=False,
    )
    op.create_index(op.f("ix_users_is_deleted"), "users", ["is_deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_deleted"), table_name="users")
    op.drop_index("ix_users_is_active_is_deleted", table_name="users")
    op.drop_column("users", "is_deleted")
    op.drop_index("ix_threat_feeds_is_deleted", table_name="threat_feeds")
    op.drop_column("threat_feeds", "is_deleted")
    op.drop_index(op.f("ix_threat_alerts_is_deleted"), table_name="threat_alerts")
    op.drop_column("threat_alerts", "is_deleted")
    op.drop_index(
        op.f("ix_security_advisors_is_deleted"), table_name="security_advisors"
    )
    op.drop_column("security_advisors", "is_deleted")
    op.drop_index("ix_ioc_is_deleted", table_name="indicators_of_compromise")
    op.drop_index(
        op.f("ix_indicators_of_compromise_is_deleted"),
        table_name="indicators_of_compromise",
    )
    op.drop_column("indicators_of_compromise", "is_deleted")
    op.drop_index(op.f("ix_fraud_reports_is_deleted"), table_name="fraud_reports")
    op.drop_column("fraud_reports", "is_deleted")
    op.drop_index("ix_chat_sessions_is_deleted", table_name="chat_sessions")
    op.drop_column("chat_sessions", "is_deleted")
    op.drop_index("ix_chat_messages_is_deleted", table_name="chat_messages")
    op.drop_column("chat_messages", "is_deleted")
    op.drop_index("ix_breach_exposures_is_deleted", table_name="breach_exposures")
    op.drop_column("breach_exposures", "is_deleted")
    # ### end Alembic commands ###
