"""inital migration

Revision ID: 9b28535849de
Revises: 
Create Date: 2025-12-02 21:14:08.444174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b28535849de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators_of_compromise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('threat_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('threat_categories', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sighting_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_ioc_severity_valid'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='ck_ioc_confidence_score_range'),
    sa.CheckConstraint('length(threat_name) > 0', name='ck_ioc_threat_name_not_empty'),
    sa.CheckConstraint('length(value) > 0', name='ck_ioc_value_not_empty'),
    sa.CheckConstraint('sighting_count >= 0', name='ck_ioc_sighting_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_of_compromise_id'), 'indicators_of_compromise', ['id'], unique=False)
    op.create_index(op.f('ix_indicators_of_compromise_value'), 'indicators_of_compromise', ['value'], unique=False)
    op.create_index('ix_ioc_last_seen_severity', 'indicators_of_compromise', ['last_seen', 'severity'], unique=False)
    op.create_index('ix_ioc_source_source_id', 'indicators_of_compromise', ['source', 'source_id'], unique=False)
    op.create_index('ix_ioc_type_severity', 'indicators_of_compromise', ['type', 'severity'], unique=False)
    op.create_index('ix_ioc_value_type', 'indicators_of_compromise', ['value', 'type'], unique=False)
    op.create_table('security_advisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=False),
    sa.Column('certifications', sa.Text(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('max_load', sa.Integer(), nullable=False),
    sa.Column('available_hours', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_load <= max_load', name='ck_security_advisors_current_load_lte_max'),
    sa.CheckConstraint('current_load >= 0', name='ck_security_advisors_current_load_positive'),
    sa.CheckConstraint('experience_years >= 0', name='ck_security_advisors_experience_years_positive'),
    sa.CheckConstraint('length(email) > 0', name='ck_security_advisors_email_not_empty'),
    sa.CheckConstraint('length(name) > 0', name='ck_security_advisors_name_not_empty'),
    sa.CheckConstraint('max_load > 0', name='ck_security_advisors_max_load_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_advisors_email'), 'security_advisors', ['email'], unique=True)
    op.create_index('ix_security_advisors_email_is_available', 'security_advisors', ['email', 'is_available'], unique=False)
    op.create_index(op.f('ix_security_advisors_id'), 'security_advisors', ['id'], unique=False)
    op.create_index('ix_security_advisors_is_available_current_load', 'security_advisors', ['is_available', 'current_load'], unique=False)
    op.create_table('threat_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('threat_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('affected_users', sa.Text(), nullable=False),
    sa.Column('affected_ips', sa.Text(), nullable=False),
    sa.Column('affected_domains', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_status', sa.String(length=50), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("resolution_status IN ('open', 'investigating', 'resolved', 'closed', 'false_positive')", name='ck_threat_alerts_resolution_status_valid'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_threat_alerts_severity_valid'),
    sa.CheckConstraint('length(threat_type) > 0', name='ck_threat_alerts_threat_type_not_empty'),
    sa.CheckConstraint('length(title) > 0', name='ck_threat_alerts_title_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threat_alerts_created_at_severity', 'threat_alerts', ['created_at', 'severity'], unique=False)
    op.create_index(op.f('ix_threat_alerts_id'), 'threat_alerts', ['id'], unique=False)
    op.create_index('ix_threat_alerts_is_acknowledged_is_active', 'threat_alerts', ['is_acknowledged', 'is_active'], unique=False)
    op.create_index('ix_threat_alerts_is_active_severity', 'threat_alerts', ['is_active', 'severity'], unique=False)
    op.create_index('ix_threat_alerts_resolution_status_is_active', 'threat_alerts', ['resolution_status', 'is_active'], unique=False)
    op.create_index('ix_threat_alerts_threat_type_severity', 'threat_alerts', ['threat_type', 'severity'], unique=False)
    op.create_table('threat_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('feed_type', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(feed_type) > 0', name='ck_threat_feeds_feed_type_not_empty'),
    sa.CheckConstraint('length(name) > 0', name='ck_threat_feeds_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_feeds_id'), 'threat_feeds', ['id'], unique=False)
    op.create_index('ix_threat_feeds_is_active_feed_type', 'threat_feeds', ['is_active', 'feed_type'], unique=False)
    op.create_index('ix_threat_feeds_last_updated', 'threat_feeds', ['last_updated'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('is_vulnerable', sa.Boolean(), nullable=False),
    sa.Column('vulnerability_factors', sa.Text(), nullable=False),
    sa.Column('vulnerability_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('total_breaches', sa.Integer(), nullable=False),
    sa.Column('total_phishing_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('age IS NULL OR age > 0', name='ck_users_age_positive'),
    sa.CheckConstraint('length(email) > 0', name='ck_users_email_not_empty'),
    sa.CheckConstraint('length(name) > 0', name='ck_users_name_not_empty'),
    sa.CheckConstraint('risk_score >= 0.0 AND risk_score <= 100.0', name='ck_users_risk_score_range'),
    sa.CheckConstraint('total_breaches >= 0', name='ck_users_total_breaches_positive'),
    sa.CheckConstraint('total_phishing_attempts >= 0', name='ck_users_total_phishing_attempts_positive'),
    sa.CheckConstraint('vulnerability_score >= 0.0 AND vulnerability_score <= 100.0', name='ck_users_vulnerability_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_is_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_is_vulnerable_risk_score', 'users', ['is_vulnerable', 'risk_score'], unique=False)
    op.create_index('ix_users_role_is_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('breach_exposures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breach_name', sa.String(length=255), nullable=False),
    sa.Column('breach_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('breach_description', sa.Text(), nullable=True),
    sa.Column('data_classes', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_breach_exposures_severity_valid'),
    sa.CheckConstraint('length(breach_name) > 0', name='ck_breach_exposures_breach_name_not_empty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_breach_exposures_breach_date_severity', 'breach_exposures', ['breach_date', 'severity'], unique=False)
    op.create_index(op.f('ix_breach_exposures_id'), 'breach_exposures', ['id'], unique=False)
    op.create_index('ix_breach_exposures_source_source_id', 'breach_exposures', ['source', 'source_id'], unique=False)
    op.create_index(op.f('ix_breach_exposures_user_id'), 'breach_exposures', ['user_id'], unique=False)
    op.create_index('ix_breach_exposures_user_id_severity', 'breach_exposures', ['user_id', 'severity'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('vulnerability_factors', sa.Text(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('escalated_to', sa.String(length=255), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high', 'critical')", name='ck_chat_sessions_risk_level_valid'),
    sa.CheckConstraint("status IN ('active', 'closed', 'escalated', 'archived')", name='ck_chat_sessions_status_valid'),
    sa.CheckConstraint('length(session_id) > 0', name='ck_chat_sessions_session_id_not_empty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_sessions_created_at_status', 'chat_sessions', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    op.create_index('ix_chat_sessions_status_risk_level', 'chat_sessions', ['status', 'risk_level'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index('ix_chat_sessions_user_id_status', 'chat_sessions', ['user_id', 'status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.Text(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('user_feedback', sa.String(length=50), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("message_type IN ('user', 'assistant', 'system', 'error')", name='ck_chat_messages_message_type_valid'),
    sa.CheckConstraint("user_feedback IS NULL OR user_feedback IN ('positive', 'negative', 'neutral')", name='ck_chat_messages_user_feedback_valid'),
    sa.CheckConstraint('ai_confidence IS NULL OR (ai_confidence >= 0.0 AND ai_confidence <= 1.0)', name='ck_chat_messages_ai_confidence_range'),
    sa.CheckConstraint('length(content) > 0', name='ck_chat_messages_content_not_empty'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_ai_model_ai_confidence', 'chat_messages', ['ai_model', 'ai_confidence'], unique=False)
    op.create_index('ix_chat_messages_created_at_message_type', 'chat_messages', ['created_at', 'message_type'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index('ix_chat_messages_session_id_message_type', 'chat_messages', ['session_id', 'message_type'], unique=False)
    op.create_table('fraud_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('fraud_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('evidence_files', sa.Text(), nullable=False),
    sa.Column('evidence_links', sa.Text(), nullable=False),
    sa.Column('financial_loss', sa.Float(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high', 'critical')", name='ck_fraud_reports_risk_level_valid'),
    sa.CheckConstraint("status IN ('open', 'investigating', 'resolved', 'closed', 'false_positive')", name='ck_fraud_reports_status_valid'),
    sa.CheckConstraint('financial_loss IS NULL OR financial_loss >= 0', name='ck_fraud_reports_financial_loss_positive'),
    sa.CheckConstraint('length(description) > 0', name='ck_fraud_reports_description_not_empty'),
    sa.CheckConstraint('length(fraud_type) > 0', name='ck_fraud_reports_fraud_type_not_empty'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fraud_reports_fraud_type_risk_level', 'fraud_reports', ['fraud_type', 'risk_level'], unique=False)
    op.create_index(op.f('ix_fraud_reports_id'), 'fraud_reports', ['id'], unique=False)
    op.create_index('ix_fraud_reports_reported_at_status', 'fraud_reports', ['reported_at', 'status'], unique=False)
    op.create_index(op.f('ix_fraud_reports_session_id'), 'fraud_reports', ['session_id'], unique=False)
    op.create_index('ix_fraud_reports_status_assigned_to', 'fraud_reports', ['status', 'assigned_to'], unique=False)
    op.create_index(op.f('ix_fraud_reports_user_id'), 'fraud_reports', ['user_id'], unique=False)
    op.create_index('ix_fraud_reports_user_id_status', 'fraud_reports', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fraud_reports_user_id_status', table_name='fraud_reports')
    op.drop_index(op.f('ix_fraud_reports_user_id'), table_name='fraud_reports')
    op.drop_index('ix_fraud_reports_status_assigned_to', table_name='fraud_reports')
    op.drop_index(op.f('ix_fraud_reports_session_id'), table_name='fraud_reports')
    op.drop_index('ix_fraud_reports_reported_at_status', table_name='fraud_reports')
    op.drop_index(op.f('ix_fraud_reports_id'), table_name='fraud_reports')
    op.drop_index('ix_fraud_reports_fraud_type_risk_level', table_name='fraud_reports')
    op.drop_table('fraud_reports')
    op.drop_index('ix_chat_messages_session_id_message_type', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_created_at_message_type', table_name='chat_messages')
    op.drop_index('ix_chat_messages_ai_model_ai_confidence', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_chat_sessions_user_id_status', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_status_risk_level', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_created_at_status', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_breach_exposures_user_id_severity', table_name='breach_exposures')
    op.drop_index(op.f('ix_breach_exposures_user_id'), table_name='breach_exposures')
    op.drop_index('ix_breach_exposures_source_source_id', table_name='breach_exposures')
    op.drop_index(op.f('ix_breach_exposures_id'), table_name='breach_exposures')
    op.drop_index('ix_breach_exposures_breach_date_severity', table_name='breach_exposures')
    op.drop_table('breach_exposures')
    op.drop_index('ix_users_role_is_active', table_name='users')
    op.drop_index('ix_users_is_vulnerable_risk_score', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email_is_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_threat_feeds_last_updated', table_name='threat_feeds')
    op.drop_index('ix_threat_feeds_is_active_feed_type', table_name='threat_feeds')
    op.drop_index(op.f('ix_threat_feeds_id'), table_name='threat_feeds')
    op.drop_table('threat_feeds')
    op.drop_index('ix_threat_alerts_threat_type_severity', table_name='threat_alerts')
    op.drop_index('ix_threat_alerts_resolution_status_is_active', table_name='threat_alerts')
    op.drop_index('ix_threat_alerts_is_active_severity', table_name='threat_alerts')
    op.drop_index('ix_threat_alerts_is_acknowledged_is_active', table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_id'), table_name='threat_alerts')
    op.drop_index('ix_threat_alerts_created_at_severity', table_name='threat_alerts')
    op.drop_table('threat_alerts')
    op.drop_index('ix_security_advisors_is_available_current_load', table_name='security_advisors')
    op.drop_index(op.f('ix_security_advisors_id'), table_name='security_advisors')
    op.drop_index('ix_security_advisors_email_is_available', table_name='security_advisors')
    op.drop_index(op.f('ix_security_advisors_email'), table_name='security_advisors')
    op.drop_table('security_advisors')
    op.drop_index('ix_ioc_value_type', table_name='indicators_of_compromise')
    op.drop_index('ix_ioc_type_severity', table_name='indicators_of_compromise')
    op.drop_index('ix_ioc_source_source_id', table_name='indicators_of_compromise')
    op.drop_index('ix_ioc_last_seen_severity', table_name='indicators_of_compromise')
    op.drop_index(op.f('ix_indicators_of_compromise_value'), table_name='indicators_of_compromise')
    op.drop_index(op.f('ix_indicators_of_compromise_id'), table_name='indicators_of_compromise')
    op.drop_table('indicators_of_compromise')
    # ### end Alembic commands ###
